---
abstract: 'Automatically enable coercions for Moose attributes'
author:
  - 'Rafael Kitover <rkitover@cpan.org>'
  - 'Michael G. Schwern <mschwern@cpan.org>'
  - 'Karen Etheridge <ether@cpan.org>'
build_requires:
  Test::CheckDeps: 0.002
  Test::Fatal: 0
  Test::More: 0.88
  Test::NoWarnings: 1.04
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300016, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: MooseX-AlwaysCoerce
requires:
  Carp: 0
  Moose: 0
  MooseX::ClassAttribute: 0.24
  Package::Stash: 0.26
  namespace::autoclean: 0.12
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=MooseX-AlwaysCoerce
  repository: git://git.moose.perl.org/MooseX-AlwaysCoerce.git
version: 0.17
x_Dist_Zilla:
  plugins:
    -
      class: Dist::Zilla::Plugin::Git::NextVersion
      name: Git::NextVersion
      version: 1.121010
    -
      class: Dist::Zilla::Plugin::MetaResources
      name: MetaResources
      version: 4.300016
    -
      class: Dist::Zilla::Plugin::GatherDir
      name: '@Basic/GatherDir'
      version: 4.300016
    -
      class: Dist::Zilla::Plugin::PruneCruft
      name: '@Basic/PruneCruft'
      version: 4.300016
    -
      class: Dist::Zilla::Plugin::ManifestSkip
      name: '@Basic/ManifestSkip'
      version: 4.300016
    -
      class: Dist::Zilla::Plugin::MetaYAML
      name: '@Basic/MetaYAML'
      version: 4.300016
    -
      class: Dist::Zilla::Plugin::License
      name: '@Basic/License'
      version: 4.300016
    -
      class: Dist::Zilla::Plugin::Readme
      name: '@Basic/Readme'
      version: 4.300016
    -
      class: Dist::Zilla::Plugin::ExtraTests
      name: '@Basic/ExtraTests'
      version: 4.300016
    -
      class: Dist::Zilla::Plugin::ExecDir
      name: '@Basic/ExecDir'
      version: 4.300016
    -
      class: Dist::Zilla::Plugin::ShareDir
      name: '@Basic/ShareDir'
      version: 4.300016
    -
      class: Dist::Zilla::Plugin::MakeMaker
      name: '@Basic/MakeMaker'
      version: 4.300016
    -
      class: Dist::Zilla::Plugin::Manifest
      name: '@Basic/Manifest'
      version: 4.300016
    -
      class: Dist::Zilla::Plugin::TestRelease
      name: '@Basic/TestRelease'
      version: 4.300016
    -
      class: Dist::Zilla::Plugin::ConfirmRelease
      name: '@Basic/ConfirmRelease'
      version: 4.300016
    -
      class: Dist::Zilla::Plugin::UploadToCPAN
      name: '@Basic/UploadToCPAN'
      version: 4.300016
    -
      class: Dist::Zilla::Plugin::Prereqs
      config:
        Dist::Zilla::Plugin::Prereqs:
          phase: runtime
          type: requires
      name: RuntimeRequires
      version: 4.300016
    -
      class: Dist::Zilla::Plugin::Prereqs
      config:
        Dist::Zilla::Plugin::Prereqs:
          phase: test
          type: requires
      name: TestRequires
      version: 4.300016
    -
      class: Dist::Zilla::Plugin::InstallGuide
      name: InstallGuide
      version: 1.101461
    -
      class: Dist::Zilla::Plugin::MetaConfig
      name: MetaConfig
      version: 4.300016
    -
      class: Dist::Zilla::Plugin::MetaJSON
      name: MetaJSON
      version: 4.300016
    -
      class: Dist::Zilla::Plugin::PkgVersion
      name: PkgVersion
      version: 4.300016
    -
      class: Dist::Zilla::Plugin::NoTabsTests
      name: NoTabsTests
      version: 0.01
    -
      class: Dist::Zilla::Plugin::EOLTests
      name: EOLTests
      version: 0.02
    -
      class: Dist::Zilla::Plugin::Test::Compile
      name: Test::Compile
      version: 1.112820
    -
      class: Dist::Zilla::Plugin::Test::DistManifest
      name: Test::DistManifest
      version: 2.0.1
    -
      class: Dist::Zilla::Plugin::Test::MinimumVersion
      name: Test::MinimumVersion
      version: 2.0.1
    -
      class: Dist::Zilla::Plugin::Test::CPAN::Changes
      name: Test::CPAN::Changes
      version: 0.005
    -
      class: Dist::Zilla::Plugin::Test::ChangesHasContent
      name: Test::ChangesHasContent
      version: 0.005
    -
      class: Dist::Zilla::Plugin::Test::CheckDeps
      name: Test::CheckDeps
      version: 0.005
    -
      class: Dist::Zilla::Plugin::PodSyntaxTests
      name: PodSyntaxTests
      version: 4.300016
    -
      class: Dist::Zilla::Plugin::CheckPrereqsIndexed
      name: CheckPrereqsIndexed
      version: 0.007
    -
      class: Dist::Zilla::Plugin::Git::Remote::Check
      name: Git::Remote::Check
      version: 0.1.2
    -
      class: Dist::Zilla::Plugin::Git::Check
      name: Git::Check
      version: 1.121010
    -
      class: Dist::Zilla::Plugin::Git::CheckFor::CorrectBranch
      name: Git::CheckFor::CorrectBranch
      version: 0.004
    -
      class: Dist::Zilla::Plugin::NextRelease
      name: NextRelease
      version: 4.300016
    -
      class: Dist::Zilla::Plugin::Git::Commit
      name: Git::Commit
      version: 1.121010
    -
      class: Dist::Zilla::Plugin::Git::Tag
      name: Git::Tag
      version: 1.121010
    -
      class: Dist::Zilla::Plugin::Git::Push
      name: Git::Push
      version: 1.121010
    -
      class: Dist::Zilla::Plugin::InstallRelease
      name: InstallRelease
      version: 0.008
    -
      class: Dist::Zilla::Plugin::Clean
      name: Clean
      version: 0.03
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':InstallModules'
      version: 4.300016
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':IncModules'
      version: 4.300016
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':TestFiles'
      version: 4.300016
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ExecFiles'
      version: 4.300016
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ShareFiles'
      version: 4.300016
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':MainModule'
      version: 4.300016
  zilla:
    class: Dist::Zilla::Dist::Builder
    config:
      is_trial: 0
    version: 4.300016
