---
abstract: 'Automatically enable coercions for Moose attributes'
author:
  - 'Rafael Kitover, C<< <rkitover at cpan.org> >>'
  - 'Rafael Kitover <rkitover@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::Fatal: 0
  Test::More: 0.94
  Test::NoWarnings: 0
  Test::Requires: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: MooseX-AlwaysCoerce
no_index:
  directory:
    - inc
    - t
provides:
  MooseX::AlwaysCoerce:
    file: lib/MooseX/AlwaysCoerce.pm
    version: 0.16
  MooseX::AlwaysCoerce::Role::Meta::Attribute:
    file: lib/MooseX/AlwaysCoerce.pm
  MooseX::AlwaysCoerce::Role::Meta::Class:
    file: lib/MooseX/AlwaysCoerce.pm
requires:
  Moose: 0
  MooseX::ClassAttribute: 0.24
  Package::Stash: 0.26
  namespace::autoclean: 0.12
resources:
  license: http://dev.perl.org/licenses/
  repository: http://git.shadowcat.co.uk/gitweb/gitweb.cgi?p=gitmo/MooseX-AlwaysCoerce.git
version: 0.16
